### PR TITLE
GEODE-1549: Correct "Help" hyperlink in pulse

### PR DESCRIPTION
**Pull request by smanvi-pivotal**
The Help hyperlink in the Pulse UI was incorrect.

### CODE REVIEW

**Comment by kirklund** [comment]
Changes look good. I'll pull this in to commit!

**Comment by sboorlagadda** [comment]
@smanvi-pivotal  Shouldn`t we refer geode docs rather than gemfire? 
Eg: http://**geode.**docs.pivotal.io/**docs**/tools_modules/pulse/chapter_overview.html

**Comment by kirklund** [comment]
@sboorlagadda Yes, I missed that. Thanks Sai! @smanvi-pivotal can you please change the links to point at corresponding pages under http://geode.docs.pivotal.io/docs/tools_modules/pulse/chapter_overview.html? Thanks!

**Comment by smanvi-pivotal** [comment]
Thanks for pointing out @sboorlagadda and @kirklund. Will make the change. Was not aware that there was separate documentation for Geode.

**Comment by smanvi-pivotal** [comment]
@kirklund , should I just submit a new commit and a new pull request with the correction ? Do I need to do anything with this pull request ? like discarding or something ?

**Comment by sboorlagadda** [comment]
@smanvi-pivotal The PR gets updated automatically when you push the new commit on your feature branch.

**Comment by jinmeiliao** [comment]
+1

**Comment by sboorlagadda** [comment]
+1

**Comment by jinmeiliao** [comment]
I'll pull this

**Pull request closed without merging**
