### PR TITLE
Feature/geode 2015

### PR DESCRIPTION
**Pull request by joeymcallister**
Changes to docs and site directories for adding the documentation/user guide to the Geode website.

### CODE REVIEW

**Comment by upthewaterspout** [comment]
Changes look good. I think there needs to be some changes to geode-site/website/README.md to instruct people to build the docs and include them in the website though. Otherwise someone might build and push the website with the docs missing.

**Comment by joeymcallister** [comment]
Agreed. Working on that now. Thanks!

**Comment by davebarnes97** [comment]
Correction - bookbinder watch did not work reliably for me, so this PR does not introduce a new problem.
Re-verified that local bind yields good output.

IMO, OK to accept this PR.

**Comment by karensmolermiller** [comment]
+1 on this PR with two minor alterations in the `geode-book/README.md` file:

- the markdown is not quite right. Adding appropriate blank lines and indenting the fixed width text sections by 4 spaces will make the last section's 4 numbered items appear as 1, 2, 3, 4.  They currently appear as 1, 1, 1, 1.
- the first of the 3 commands to embed the User Guide into the website content (what will be step number 2) is missing a period at the end of the command.
The *incorrect* commands:

```
   $ tar cvf ~/Desktop/new-guide-content.tar
   $ cd ../../../geode-site/content
   $ tar xvf ~/Desktop/new-guide-content.tar
```

The correct commands are

```
   $ tar cvf ~/Desktop/new-guide-content.tar .
   $ cd ../../../geode-site/content
   $ tar xvf ~/Desktop/new-guide-content.tar
```

_Note:_  when merging in this PR to a current develop branch, there will be a conflict (as noted in the PR) on the subnav.  Keep the develop branch's (new) link to the Automated Rebalance section, but update its path to include `/guide`.

**Comment by joeymcallister** [comment]
@karensmolermiller I committed a new README.md file with the two changes you suggested. My markdown editors showed the correct formatting before the changes, as well as after the changes. Please review to make sure they're registering in your markdown editor.

**Pull request closed without merging**
