### PR TITLE
[GEODE-1984] #comment Fix Issue Make GatewaySender destroy a public API

### PR DESCRIPTION
**Pull request by davinash**
1. Making destory API public
2. Added a new gfsh WAN command destroyGatewaySender
3. Impleted GatewaySenderDestroyFunction, which first stop gatewaysender
   and then call destroy on the same.
4. Added a WAN Rest Controller for destroy gatewaysender
5. Removed the need of explicit casting of sender to AbstractGatewaySender for calling
   destroy API
6. Renamed Test WanCommandCreateGatewaySenderDUnitTest to WanCommandCreateDestroyGatewaySenderDUnitTest
7. Each applicable test now also calls destroy gfsh command and verfies the result
8. Minor changes in the logging for each tests

Precheckin is passing.

### CODE REVIEW

**Comment by metatype** [comment]
@davinash I think you merged `master` into your feature branch.  I suggest closing this PR and starting a new one.

**Comment by davinash** [comment]
Hi @metatype Could you please deleting branch GEODE-1984 from master. I am getting error.
git flow feature start GEODE-1984
Fatal: Branch 'feature/GEODE-1984' already exists. Pick another name.

**Comment by metatype** [comment]
`git push origin --delete feature/GEODE-1984`.

You should also confirm that you've deleted the branch from your _local_ repo (`git branch -D feature/GEODE-1984`).  Are you still having problems with write access?

**Comment by davinash** [comment]
I have no problem with write access and have deleted local branch. But I get following error.
```
git push origin --delete feature/GEODE-1984
error: unable to delete 'feature/GEODE-1984': remote ref does not exist
error: failed to push some refs to 'https://git-wip-us.apache.org/repos/asf/incubator-geode.git'
```

**Comment by metatype** [comment]
Sorry, I meant to write "I delete the remote branch for you".  :-)

**Pull request closed without merging**
