### PR TITLE
Addresses the documentation component of GEODE-268, adding explanatio…

### PR DESCRIPTION
**Pull request by davebarnes97**
…n to the Javadoc for OperationContext.isClientUpdate().

### CODE REVIEW

**Comment by kirklund** [comment]
I'll take this PR.

**Comment by upthewaterspout** [comment]
Looks like these {@linkplain } links are causing javadoc warns when this is merged to the latest develop:

./gradlew gemfire-core:javadoc

/home/dsmith/data/work/gemfire/open/gemfire-core/src/main/java/com/gemstone/gemfire/cache/operations/OperationContext.java:492: warning - Tag @link: missing '#': "getOperationCode()"

**Comment by davebarnes97** [comment]
Kirk & Dan,
Thanks for trying, guys. I'll revisit & revise.
Dave

**Comment by davebarnes97** [comment]
Links replaced with simple font changes - should build without error.

**Pull request closed without merging**
