### PR TITLE
GEODE-511 Pulse: Residual 'Gemfire' changed to 'Geode'

### PR DESCRIPTION
**Pull request by nitin-amp**
Change **Gemfire** in Pulse UI to **Geode**

### CODE REVIEW

**Comment by upthewaterspout** [comment]
+1

**Comment by jinmeiliao** [comment]
+1

**Comment by nitin-amp** [comment]
Thanks for +1's. Is anything pending to merge this?

**Comment by upthewaterspout** [comment]
I'll merge this.

**Pull request closed without merging**
