### PR TITLE
GEODE-2092: Security examples should not be in the product code

### PR DESCRIPTION
**Pull request by kjduling**
Moved examples to geode-core/src/main/java/org/apache/geode/examples/security/
Copied old Sample/Simple code to test packages as many tests rely on these classes.
Deleted SimpleSecurityManager example class

### CODE REVIEW

**Comment by kjduling** [comment]
Merged in latest develop branch.  Precheckin running.

**Comment by kjduling** [comment]
Confict fixed.  Precheckin running.

**Comment by metatype** [comment]
@kjduling Is this ready to be merged?

**Comment by kjduling** [comment]
@metatype Yes, precheckin ran clean.

**Comment by jinmeiliao** [comment]
I'll pull this in.

**Pull request closed without merging**
