### PR TITLE
GEODE-866: Converting calls of vm.invoke to lambdas

### PR DESCRIPTION
**Pull request by upthewaterspout**
I automatically converted many of the calls of vm.invoke(Class, String) to use a lambda instead, as discussed. Please review this PR - I think it will be easier to review the individual commits than a review board post.

There were a few roadblocks along the way:
- I changed SerializableRunnableIF to throw an exception from the run method. That made it easier to write short lambda expressions without having to put in a try catch in the lambda. 
- I had to modify some tests to make variables effectively final, or not refer to a static inside the lambda, and a few other issues to get all of the tests to compile and pass. See my individual commits.

Not all vm.invoke calls are gone, unfortunately. There are a number of places that could not be automatically converted - mostly where the code built up an object array in a weird way and then passed it to invoke. We'll have to manually fix these.

### CODE REVIEW

**Comment by upthewaterspout** [comment]
BTW - I can push this change myself, I just thought it would be easier to review as a PR than a reviewboard request. If I get a couple of +1s and no -1s in the next day or so I'll push it.

**Comment by jdeppe-pivotal** [comment]
+1 Awesome!

**Comment by sboorlagadda** [comment]
+1

**Comment by kirklund** [comment]
+1 changes look great

**Comment by bschuchardt** [comment]
+1 very nice

**Comment by jinmeiliao** [comment]
+1 great

**Pull request merged**
