### PR TITLE
GEODE-1682: Adding options for starting Geode REST API using gfsh

### PR DESCRIPTION
**Pull request by davinash**
GEODE-1682: 

- Added option in gfsh to start REST `start-rest-api`
- Added option for http service port `http-service-port`
- Added option for http service bind address `http-service-bind-address`
- Update `gemfireProperties` to for `cache` creation.
- Verified Manually ( both with `start-rest-api` and without )
- Ran the precheckin 
   - Test Failing ( ConcurrentParallelGatewaySenderOffHeapDUnitTest#testPartitionedParallelPropagationHA

### CODE REVIEW

**Comment by kirklund** [comment]
Thank you for the pull request Avinash! Please look into writing some new tests that verify the changes.

**Comment by davinash** [comment]
Thanks @kirklund for initial review. I have updated the PR with addition of Tests

**Comment by sbawaska** [comment]
+1

**Comment by davinash** [comment]
what is the next step for merge, I do not see that option. May be I am missing something !!!

**Comment by kirklund** [comment]
I'll merge it to develop, run tests and commit it if everything passes -- the commit will automatically close the PR and you'll receive a notification. Thanks Avinash!

**Comment by kirklund** [comment]
Hi @davinash, there was one test failure in precheckin that needs to be fixed:
<pre>
:geode-core:integrationTest

com.gemstone.gemfire.management.internal.cli.commands.HelpCommandsIntegrationTest > testOfflineHelp FAILED
    org.junit.ComparisonFailure: expected:<...iguration(=value)?]
    [PARAMETERS
<...snip...>
        use-cluster-configuration
            When set to true, the server requests the configuration from locator's cluster
            configuration service.
            Required: false
            Default (if the parameter is specified without value): true
            Default (if the parameter is not specified): true
        start-rest-api
            When set to true, will start the REST API service.
            Required: false
            Default (if the parameter is specified without value): true
            Default (if the parameter is not specified): false
        http-service-port
            Port on which HTTP Service will listen on
            Required: false
            Default (if the parameter is not specified): 8080
        http-service-bind-address
            The IP address on which the HTTP Service will be bound.  By default, the Server is bound to
            all local addresses.
            Required: fals]e>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at com.gemstone.gemfire.management.internal.cli.commands.HelpCommandsIntegrationTest.testOfflineHelp(HelpCommandsIntegrationTest.java:100)

3229 tests completed, 1 failed, 175 skipped
:geode-core:integrationTest FAILED
</pre>

**Pull request closed without merging**
