### PR TITLE
GEODE-2098: Moved gfsh history file location from .gemfire to .geode

### PR DESCRIPTION
**Pull request by davinash**
Made the code changes and added a test for the same.

Following Test is failing with precheckin, but works fine when ran individually.
org.apache.geode.internal.statistics.DiskSpaceLimitIntegrationTest

### CODE REVIEW

**Comment by kirklund** [comment]
Since Geode 1.0 released using .gemfire history file, we should probably read and use .gemfire if .geode does not exist. If both files exist then .geode should take precedence.

What OS does DiskSpaceLimitIntegrationTest fail on for you?

**Comment by kirklund** [comment]
I recommend discussing backwards compatibility of .gemfire vs .geode directory (which contains gfsh history file) on the dev list. I don't really feel strongly one way or the other (supporting .gemfire vs just a hard switch to .geode). Dev list is good place to discuss backwards compatibility though.

**Comment by upthewaterspout** [comment]
IMO losing your gfsh history on an upgrade is probably not a big deal.

**Comment by metatype** [comment]
Agreed.  This could be handled in a release note:  “If you want to preserve your gfsh history, please copy…”

Anthony

**Comment by davinash** [comment]
@kirklund 
What OS does DiskSpaceLimitIntegrationTest fail on for you?
[ Avinash ] Linux

**Comment by davinash** [comment]
Thanks @kirklund @metatype @upthewaterspout. Do I need to mark the JIRA for release notes ? If not I will merge this PR, please let me know.

**Comment by kirklund** [comment]
+1 looks ready to push to develop. 

Once it's committed on develop, then mark the Jira ticket Resolved (not Closed) and Fix Version(s) should say 1.1.0-incubating. When 1.1.0 is released, all Resolved tickets are moved to Closed (all such tickets will be part of release notes automatically I think).

**Comment by davinash** [comment]
Thanks @kirklund, @metatype I have followed the process from https://cwiki.apache.org/confluence/display/GEODE/Code+contributions
Please do let me know if everything is correct.

**Comment by kirklund** [comment]
I tried to pull this in but I get an error message about the branch not existing:

fatal: Couldn't find remote ref feature/GEODE-2098

Looks like the pull request is still open, but the branch has been destroyed.

**Comment by davinash** [comment]
closing the pull request.

**Pull request closed without merging**
