### PR TITLE
Port projectgeode.org

### PR DESCRIPTION
**Pull request by jacksoncvm**

### CODE REVIEW

**Comment by rvs** [comment]
@jacksoncvm thanks for the update! Two major points:
   * can you please make sure that Apache Geode is referred to as Apache Geode (incubating) at least for the first time we mention it on the page and definitely on the footers/headers/etc.
   * I still see tons of references to pivotal.io, etc. Can you please fix those links so they point to our ASF infrastructure?

**Comment by jacksoncvm** [comment]
I thought Greg Chase was going to make those changes, but yes, I can.

-Chloe

**Comment by jacksoncvm** [comment]
What should replace https://network.pivotal.io/products/project-geode (ie.
where are downloads now)? Should we change
https://support.pivotal.io/hc/communities/public/topics/200053218-Pivotal-GemFire-Forum
to something else?  Those are the only 2 pivotal.io links I see...

-Chloe

**Comment by jacksoncvm** [comment]
I was expecting infrastructure similar to the github check in / check out.
I basically need someone to set me up and show me how to do this :)

On Thu, May 7, 2015 at 11:56 AM, Chloe Jackson <cjackson@pivotal.io> wrote:

> What should replace https://network.pivotal.io/products/project-geode
> (ie. where are downloads now)? Should we change
> https://support.pivotal.io/hc/communities/public/topics/200053218-Pivotal-GemFire-Forum
> to something else?  Those are the only 2 pivotal.io links I see...
>
> -Chloe
>
> On Thu, May 7, 2015 at 11:51 AM, Chloe Jackson <cjackson@pivotal.io>
> wrote:
>
>> I thought Greg Chase was going to make those changes, but yes, I can.
>>
>> -Chloe
>>
>> On Thu, May 7, 2015 at 11:49 AM, Roman V Shaposhnik <
>> notifications@github.com> wrote:
>>
>>> @jacksoncvm <https://github.com/jacksoncvm> thanks for the update! Two
>>> major points:
>>>
>>>    - can you please make sure that Apache Geode is referred to as
>>>    Apache Geode (incubating) at least for the first time we mention it on the
>>>    page and definitely on the footers/headers/etc.
>>>    - I still see tons of references to pivotal.io, etc. Can you please
>>>    fix those links so they point to our ASF infrastructure?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/apache/incubator-geode/pull/3#issuecomment-99975911>
>>> .
>>>
>>
>>
>


-- 
Greg Chase

Director of Product Marketing | Big Data
http://www.pivotal.io/big-data

Pivotal Software
http://www.pivotal.io/

650-215-0477
@GregChase
Blog: http://geekmarketing.biz/

**Pull request closed without merging**
