### PR TITLE
GEODE-341: Refactor Java packages to reflect Apache organization.

### PR DESCRIPTION
**Pull request by jujoramos**
- Root project is now "geode-jvsd".
	- Root package is now "org.apache.geode.jvsd".
	- Classes from MultiAxisChartFX were merged with the apache license header.
	- Not needed dependencies were deleted from the pom.xml to avoid polluting the project.
	- Legacy properties deleted from source, they can be added later if needed.
	- Added an information alert to handle unimplemented actions in the controllers.
	- Changed the stat list to accept multiple selections in the ScrollPane under the root panel.

### CODE REVIEW

**Comment by jdeppe-pivotal** [comment]
A couple of things:

- The MultiAxisChartFX class is GPL code and cannot have an Apache 2.0 license attached to it. This is the reason this code was in a separate repo. A user would need to build that separately and then reference it in this project.
- The readme should be updated. There is no dependency on Geode to build Jvsd.

**Comment by vfordpivotal** [comment]
A number of the pom.xml dependencies removed will need to be re-added as they will be needed for testing (creating stats files...) which at present is missing from this project. So jvsd itself doesn't require geode code itself, the testing code will need it to generate test data and to validate compatibility with geode generated stats files.

**Comment by pivotal-jbarrett** [comment]
The only changes that should be in this pull request for GEODE-341 are the changes specific to this issue. Only the package names should be changed in this pull. The other changes need to be submitted as other issues and pull requests.

**Comment by jujoramos** [comment]
Thanks all, I'll close this pull request and start a new one from scratch containing ONLY the package renaming.

**Pull request closed without merging**
