### PR TITLE
[GEODE-224] Geode Spark connector parser is not processing type casting properly

### PR DESCRIPTION
**Pull request by vectorijk**
This issue is related to wrong regex of query string.

### CODE REVIEW

**Comment by vectorijk** [comment]
cc @markito

**Comment by jhuynh1** [comment]
The changes look good, I've merged them in.

Thanks for the contribution!

**Comment by markito** [comment]
@vectorijk good catch! Thanks!

**Comment by vectorijk** [comment]
@jhuynh1 @markito Thanks for the review!

**Pull request closed without merging**
