### PR TITLE
GEODE-342: Make changes to Geode gradle build script to also build JVSD

### PR DESCRIPTION
**Pull request by jujoramos**
- Switched from maven to gradle.
- Modified global gradle script to include geode-jvsd in the build and distribution.
- Added individual tasks to clone, compile and install MultiAxisChartFX in the build process.

### CODE REVIEW

**Comment by vfordpivotal** [comment]
Reviewing the changes. The main issues might be the inclusion in the build process the cloning and building of the MultiAxisChartFX as the gpl license may be problematic.

**Comment by jujoramos** [comment]
Hey Vince,
Thanks for reviewing the pull request.
I knew about the license problem regarding project MultiAxisChartFX but we'll need to create a new JIRA to address this, instead of reimplementing the logic within GEODE-342, don't you think?. We could start doing that once the build process is standardized through gradle. Please let me know.
Cheers.

**Comment by jujoramos** [comment]
Hey Vincent,
I have the option to close the pull request from my GitHub account, do you want me to close it?. Or doing so implies some type of history loosing?.
Cheers.

**Comment by jdeppe-pivotal** [comment]
Go ahead and close this - it's been integrated already.

**Comment by jujoramos** [comment]
Thanks Jens,
It's done, cheers.

**Pull request closed without merging**
