### PR TITLE
GEODE-1615: gfsh unable to destroy region that has an hyphen in its name

### PR DESCRIPTION
**Pull request by kjduling**
Added a test for whether or not the region contains a hyphen in the name.  If it does, it is necessary to wrap the region name within quotes.

### CODE REVIEW

**Comment by jinmeiliao** [comment]
the fix looks good. Where is the test?

**Comment by kjduling** [comment]
I'm doing the test in a separate checkin once I have a final decision on what characters are valid.  Right now, it appears only alphanumeric, an underscore, and a hyphen are the only valid characters allowed.  Yet we can create regions with all sorts of characters.

**Comment by jinmeiliao** [comment]
For now, add at least a test that would cover deleting a region that has "-" and "_" in it. Later, you can expand your tests that would have all sorts of allowed characters.

**Comment by kjduling** [comment]
Closing this.  The test worked the first time, but subsequent runs consistently fail.  I'll start a fresh pull request once I resolve it.

**Pull request closed without merging**
